### ISSUE TITLE
Does not load the gtk module 

### ISSUE THREAD

**Issue by JesusChapman** [suhan-paradkar/tewmux-disabled#1]
![Screenshot_20210603-082535](https://user-images.githubusercontent.com/64093255/120681928-83f9f380-c461-11eb-87da-ed7d9ebe7a07.png)

Hi friend, this happens when running a python script with gtk, why it happens?

**Comment by creepy-pasta101** [comment]
Can you specify your gtk version??

**Comment by JesusChapman** [comment]
I have gtk 2 and 3.0, I already tried and still does not work

**Comment by creepy-pasta101** [comment]
> I have gtk 2 and 3.0, I already tried and still does not work 

Try compiling gobject-introspection from source after installing from apt.....

**Comment by JesusChapman** [comment]
Ok

**Comment by creepy-pasta101** [comment]
@Yisus7u7 try executing `g-ir-scanner`
If you face any errors... Than please send the error

**Comment by JesusChapman** [comment]
I get this error :
``
➜  ~ g-ir-scanner
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/data/data/com.termux/files/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/data/data/com.termux/files/usr/lib/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/data/data/com.termux/files/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 34, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
``

**Comment by JesusChapman** [comment]
@suhan-paradkar

**Comment by creepy-pasta101** [comment]
@Yisus7u7 Now perform these steps.... DO NOT UNINSTALL gobject-introspection
```
wget https://github.com/GNOME/gobject-introspection/archive/refs/tags/1.68.0.tar.gz
tar -xvf 1.68.0.tar.gz
cd gobject-introspection-1.68.0
mkdir build && cd build
meson --prefix=$PREFIX ..
ninja
ninja install
```

**Comment by JesusChapman** [comment]
[110/163] Generating gi...b with a custom command FAILED: gir/GLib-2.0.gir                          /data/data/com.termux/files/home/gobject-introspection-1.68.0/build/tools/g-ir-scanner --output=gir/GLib-2.0.gir --no-libtool --quiet --reparse-validate --add-include-path /data/data/com.termux/files/home/gobject-introspection-1.68.0/build/gir --add-include-path /data/data/com.termux/files/home/gobject-introspection-1.68.0/gir --identifier-prefix=G --symbol-prefix=g --symbol-prefix=glib --c-include=glib.h --namespace=GLib --nsversion=2.0 --library=glib-2.0 --library=gobject-2.0 --external-library --pkg=glib-2.0 --cflags-begin -I/data/data/com.termux/files/usr/include/glib-2.0 -I/data/data/com.termux/files/usr/lib/glib-2.0/include -DGLIB_COMPILATION -D__G_I18N_LIB_H__ -DGETTEXT_PACKAGE=Dummy --cflags-end /data/data/com.termux/files/usr/include/glib-2.0/gobject/glib-types.h /data/data/com.termux/files/usr/lib/glib-2.0/include/glibconfig.h /data/data/com.termux/files/usr/include/glib-2.0/glib-unix.h /data/data/com.termux/files/usr/include/glib-2.0/glib/galloca.h /data/data/com.termux/files/usr/include/glib-2.0/glib/garray.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gasyncqueue.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gatomic.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbacktrace.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbase64.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbitlock.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbookmarkfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbytes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gcharset.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gchecksum.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gconvert.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdataset.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdate.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdatetime.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdir.h /data/data/com.termux/files/usr/include/glib-2.0/glib/genviron.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gerror.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gfileutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ggettext.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghash.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghmac.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghook.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghostutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gi18n-lib.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gi18n.h /data/data/com.termux/files/usr/include/glib-2.0/glib/giochannel.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gkeyfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/glist.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmacros.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmain.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmappedfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmarkup.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmem.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmessages.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gnode.h /data/data/com.termux/files/usr/include/glib-2.0/glib/goption.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gpattern.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gpoll.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gprimes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gprintf.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gqsort.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gquark.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gqueue.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grand.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grcbox.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grefcount.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grefstring.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gregex.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gscanner.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gsequence.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gshell.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gslice.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gslist.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gspawn.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstdio.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstrfuncs.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstring.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstringchunk.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtestutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gthread.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gthreadpool.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtimer.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtimezone.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtrashstack.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtree.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtypes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gunicode.h /data/data/com.termux/files/usr/include/glib-2.0/glib/guri.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/guuid.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gvariant.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gvarianttype.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gversion.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gversionmacros.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gwin32.h ../gir/glib-2.0.c                        Traceback (most recent call last):                  File "/data/data/com.termux/files/home/gobject-introspection-1.68.0/build/tools/g-ir-scanner", line 98, in <module>                                     from giscanner.scannermain import scanner_main  File "/data/data/com.termux/files/home/gobject-introspection-1.68.0/build/giscanner/scannermain.py", line 35, in <module>                               from giscanner.ast import Include, Namespace    File "/data/data/com.termux/files/home/gobject-introspection-1.68.0/build/giscanner/ast.py", line 29, in <module>                                       from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF                                    File "/data/data/com.termux/files/home/gobject-introspection-1.68.0/build/giscanner/sourcescanner.py", line 34, in <module>                             from giscanner._giscanner import SourceScanner as CSourceScanner                                ImportError: dlopen failed: cannot locate symbol "PyExc_RuntimeError" referenced by "/data/data/com.termux/files/home/gobject-introspection-1.68.0/build/giscanner/_giscanner.cpython-39.so"...         ninja: build stopped: subcommand failed.

**Comment by JesusChapman** [comment]
@suhan-paradkar  ._.

**Comment by JesusChapman** [comment]
pip install cpython?

**Comment by creepy-pasta101** [comment]
> pip install cpython?

Yeah do it

**Comment by JesusChapman** [comment]
It didn't work.

**Comment by JesusChapman** [comment]
Same mistake.

**Comment by JesusChapman** [comment]
@suhan-paradkar

**Comment by creepy-pasta101** [comment]
> @suhan-paradkar 

Try along with LDFLAGS=$PREFIX/lib/

**Comment by JesusChapman** [comment]
It also doesn't work

**Comment by JesusChapman** [comment]
@suhan-paradkar  :(

**Comment by JesusChapman** [comment]
I was very excited to make gtk apps with python on termux, it hurts that you can't :(

**Comment by creepy-pasta101** [comment]
Tkinter works... Actually.....

**Comment by JesusChapman** [comment]
Jajajaja, I use tkinter, but tkinter is for prqueños projects, for the project I want to do, I would be better to use gtk, since using tkinter would make things difficult

**Comment by JesusChapman** [comment]
Jajajaja, I use tkinter, but tkinter is for Small  projects, for the project I want to do, I would be better to use gtk, since using tkinter would make things difficult

**Comment by creepy-pasta101** [comment]
@Yisus7u7 .. you better see this...
https://stackoverflow.com/questions/56823857/valueerror-namespace-gtk-not-available

**Comment by creepy-pasta101** [comment]
@Yisus7u7 you need following additional packages...
`gir1.2-gtk-3.0` and `python3-gi`

**Comment by creepy-pasta101** [comment]
Closing since you require additional packages

**Comment by JesusChapman** [comment]
So, should I wait for them to compile those packages?

**Comment by creepy-pasta101** [comment]
> So, should I wait for them to compile those packages?

if you can, compile them yourself

**Comment by creepy-pasta101** [comment]
Also... both are part of existing packages...python3-gi is a part gobject-introspection and the other one is a part of gtk3...
gir1.2-gtk-3.0 currently is not present as introspection is disabled while building gtk3....

**Comment by JesusChapman** [comment]
CuerRight, so just missing gir1.2-gtk-3.0?

**Comment by creepy-pasta101** [comment]
> CuerRight, so just missing gir1.2-gtk-3.0?

yes.. but as of now... there are no plans of compiling it.... bcoz it has problems...
it compiles using target binaries instead of host binaries

**Comment by JesusChapman** [comment]
That to past, it has not been able to fix?
